import { Template } from "./interfaces"

import img267 from "../../assets/images/267.jpg";
import img268 from "../../assets/images/268.jpg";
import img1813 from "../../assets/images/1813.jpg";
import img4875 from "../../assets/images/4875.jpg";
import imgB33 from "../../assets/images/b33.jpg";
import imgB64 from "../../assets/images/b64.jpg";
import imgCandeleholder from "../../assets/images/candleholder.jpg";
import imgDSS from "../../assets/images/dss.jpg";
import imgEero from "../../assets/images/eero.jpg";
import imgHammerRed from "../../assets/images/hammer-red.jpg";
import imgHammerYellow from "../../assets/images/hammer-yellow.jpg";
import imgKoror from "../../assets/images/koror.jpg";
import imgMassimo from "../../assets/images/massimo.jpg";
import imgMg5Red from "../../assets/images/mg5-red.jpg";
import imgMg5White from "../../assets/images/mg5-white.jpg";
import imgModus from "../../assets/images/modus.jpg";
import imgP40 from "../../assets/images/p40.jpg";
import imgPelikan from "../../assets/images/pelikan.jpg";
import imgPhilippe from "../../assets/images/philippe.jpg";
import imgPlia from "../../assets/images/plia.jpg";
import imgRoger from "../../assets/images/roger.jpg";
import imgTango from "../../assets/images/tango.jpg";
import imgTogo from "../../assets/images/togo.jpg";
import imgWassily from "../../assets/images/wassily.jpg";

 export class Product implements Template {
    id: number;
    name: string;
    amount: number;
    year: number;
    cost: number;
    color: string;
    producer: string;
    image: string;
    designer: string;
    type: string;
    popularity: number;
    isInCart: boolean;
    constructor(id: number, name: string, amount: number, year: number, cost: number, color: string, producer: string, 
      image: string, designer: string, type: string, popularity: number, isInCart: boolean) {
      this.id = id;
      this.name = name;
      this.amount = amount;
      this.year = year;
      this.cost = cost;
      this.color = color;
      this.producer = producer;
      this.image = image;
      this.designer = designer;
      this.type = type;
      this.popularity = popularity;
      this.isInCart = isInCart;
    }
 }

 export const products: Product[] = [  //TODO: add id and image array and color array
  {
    id: 1,
    name: "Handkerchief",
    amount: 4,
    year: 1980,
    cost: 1100,
    color: "blue",
    producer: "KNOLL",
    image: imgMassimo,
    designer: "Massimo and Vignelli",
    type: "armchair",
    popularity: 105,
    isInCart:  false,
  },
  {
    id: 2,
    name: "Plia",
    amount: 2,
    year: 1970,
    cost: 300,
    color: "metal",
    producer: "CASTELLI",
    image: imgPlia,
    designer: "Giancarlo Piretti",
    type: "chair",
    popularity: 27,
    isInCart:  false,
  },
  {
    id: 3,
    name: "267",
    amount: 2,
    year: 1988,
    cost: 900,
    color: "",
    producer: "",
    image: img267,
    designer: "Marcel Baugier",
    type: "composition",
    popularity: 20,
    isInCart:  false,
  },
  {
    id: 4,
    name: "Tulipe",
    amount: 6,
    year: 1970,
    cost: 1600,
    color: "white",
    producer: "KNOLL",
    image: imgEero,
    designer: "Eero Saarinen",
    type: "chair",
    popularity: 84,
    isInCart:  false,
  },
  {
    id: 5,
    name: "Pelikan",
    amount: 4,
    year: 1990,
    cost: 1850,
    color: "metal",
    producer: "FRITZ HANSEN",
    image: imgPelikan,
    designer: "Niels Gammelgaard & Lars Mathiesen",
    type: "chair",
    popularity: 35,
    isInCart:  false,
  },
  {
    id: 6,
    name: "268",
    amount: 1,
    year: 1988,
    cost: 900,
    color: "",
    producer: "",
    image: img268,
    designer: "Marcel Baugier",
    type: "composition",
    popularity: 24,
    isInCart:  false,
  },
  {
    id: 7,
    name: "P40",
    amount: 3,
    year: 1980,
    cost: 1850,
    color: "red",
    producer: "",
    image: imgP40,
    designer: "Giancarlo Venghi & Gianfranco Gualtierotti",
    type: "armchair",
    popularity: 405,
    isInCart:  false,
  },
  {
    id: 8,
    name: "Hammer",
    amount: 12,
    year: 1974,
    cost: 700,
    color: "red",
    producer: "FRITZ HANSEN",
    image: imgHammerRed,
    designer: "Arne Jaconsen",
    type: "chair",
    popularity: 41,
    isInCart:  false,
  },
  {
    id: 9,
    name: "Roger Carpon",
    amount: 1,
    year: 1950,
    cost: 3000,
    color: "black",
    producer: "",
    image: imgRoger,
    designer: "Roger Carpon",
    type: "table",
    popularity: 55,
    isInCart:  false,
  },
  {
    id: 10,
    name: "B64",
    amount: 4,
    year: 1950,
    cost: 470,
    color: "yellow",
    producer: "KNOLL",
    image: imgB64,
    designer: "Marcel Breuer",
    type: "armchair",
    popularity: 63,
    isInCart:  false,
  },
  {
    id: 11,
    name: "4875",
    amount: 1,
    year: 1950,
    cost: 350,
    color: "white",
    producer: "KARTELL",
    image: img4875,
    designer: "Carlo Bartoli",
    type: "chair",
    popularity: 54,
    isInCart:  false,
  },
  {
    id: 12,
    name: "Wassily",
    amount: 1,
    year: 1970,
    cost: 2870,
    color: "black",
    producer: "KNOLL",
    image: imgWassily,
    designer: "Marcel Breuer",
    type: "armchair",
    popularity: 137,
    isInCart:  false,
  },
  {
    id: 13,
    name: "1813",
    amount: 1,
    year: 1970,
    cost: 60,
    color: "green",
    producer: "GILAC",
    image: img1813,
    designer: "",
    type: "mirror",
    popularity: 34,
    isInCart:  false,
  },
  {
    id: 14,
    name: "Hammer",
    amount: 2,
    year: 1974,
    cost: 700,
    color: "yellow",
    producer: "FRITZ HANSEN",
    image: imgHammerYellow,
    designer: "Arne Jaconsen",
    type: "chair",
    popularity: 56,
    isInCart:  false,
  },
  {
    id: 15,
    name: "Tango",
    amount: 1,
    year: 1980,
    cost: 690,
    color: "black",
    producer: "ARTELUCE",
    image: imgTango,
    designer: "Stephen Copeland",
    type: "lamp",
    popularity: 40,
    isInCart:  false,
  },
  {
    id: 16,
    name: "mg5",
    amount: 2,
    year: 1970,
    cost: 1480,
    color: "white",
    producer: "KNOLL",
    image: imgMg5White,
    designer: "Marcel Breuer",
    type: "armchair",
    popularity: 80,
    isInCart:  false,
  },
  {
    id: 17,
    name: "",
    amount: 2,
    year: 1960,
    cost: 40,
    color: "metal",
    producer: "DANSK",
    image: imgCandeleholder,
    designer: "Jens Harald Quistgaard",
    type: "candleholder",
    popularity:57,
    isInCart:  false,
  },
  {
    id: 18,
    name: "B33",
    amount: 1,
    year: 1970,
    cost: 800,
    color: "black",
    producer: "KNOLL",
    image: imgB33,
    designer: "Marcel Breuer",
    type: "chair",
    popularity: 81,
    isInCart:  false,
  },
  {
    id: 19,
    name: "Koror",
    amount: 2,
    year: 1950,
    cost: 80,
    color: "blue",
    producer: "HOLMEGAARD",
    image: imgKoror,
    designer: "Per Lutken",
    type: "vase",
    popularity: 50,
    isInCart:  false,
  },
  {
    id: 20,
    name: "Togo",
    amount: 2,
    year: 1980,
    cost: 8560,
    color: "white",
    producer: "LIGNE ROSET",
    image: imgTogo,
    designer: "Mitchel Ducaroy",
    type: "chauffeuse",
    popularity: 205,
    isInCart:  false,
  },
  {
    id: 21,
    name: "Modus",
    amount: 1,
    year: 1970,
    cost: 340,
    color: "black",
    producer: "TECNO",
    image: imgModus,
    designer: "OSVALDO BORSANI",
    type: "armchair",
    popularity: 50,
    isInCart:  false,
  },
  {
    id: 22,
    name: "mg5",
    amount: 4,
    year: 1970,
    cost: 1480,
    color: "red",
    producer: "KNOLL",
    image: imgMg5Red,
    designer: "Marcel Breuer",
    type: "armchair",
    popularity: 117,
    isInCart:  false,
  },
  {
    id: 23,
    name: "Philippe Rogier",
    amount: 2,
    year: 1970,
    cost: 270,
    color: "metal",
    producer: "OXAR",
    image: imgPhilippe,
    designer: "Philippe Rogier",
    type: "lamp",
    popularity: 90,
    isInCart:  false,
  },
  {
    id: 24,
    name: "DSS",
    amount: 6,
    year: 1980,
    cost: 845,
    color: "blue",
    producer: "VITRA",
    image: imgDSS,
    designer: "CHARLES & RAY EAMES",
    type: "chair",
    popularity: 59,
    isInCart:  false,
  },
  {
    id: 25,
    name: "41701",
    amount: 1,
    year: 1977,
    cost: 122,
    color: "black",
    producer: "OSRAM",
    image: "https://www.dropbox.com/s/1r6kjrjqx62wv5m/302187540_145305161198015_8567532113954371301_n.jpg?raw=1",
    designer: "DIETTER WITTE",
    type: "lamp",
    popularity: 39,
    isInCart:  false,
  },
  {
    id: 26,
    name: "Brumbury",
    amount: 1,
    year: 1972,
    cost: 2100,
    color: "orange",
    producer: "GUZZINI",
    image: "https://www.dropbox.com/s/addmm845i3edov1/P1550742.jpg.webp?raw=1",
    designer: "Luigi Massoni",
    type: "lamp",
    popularity: 26,
    isInCart:  false,
  },
  {
    id: 27,
    name: "Harveiluce",
    amount: 2,
    year: 1977,
    cost: 368,
    color: "white",
    producer: "GUZZINI",
    image: "https://www.dropbox.com/s/fa2yumzpcf2fm1l/296155398_144982371488711_1090905325727216530_n.jpg?raw=1",
    designer: "HARVEY GUZZINI",
    type: "lamp",
    popularity: 41,
    isInCart:  false,
  },
  {
    id: 28,
    name: "Atollo",
    amount: 1,
    year: 1973,
    cost: 1285,
    color: "bronze",
    producer: "Oluce",
    image: "https://www.objekt-vintage.nl/wp-content/uploads/2023/01/atollo-4.jpg",
    designer: "VICO MAGISTRETTI",
    type: "lamp",
    popularity: 979,
    isInCart:  false,
  },
  {
    id: 29,
    name: "Mod 4043",
    amount: 1,
    year: 1964,
    cost: 5760,
    color: "metal",
    producer: "Kartell",
    image: "https://www.objekt-vintage.nl/wp-content/uploads/2021/08/kartell-lamp-5.jpg",
    designer: "FILIPPO PANSECA",
    type: "lamp",
    popularity: 76,
    isInCart:  false,
  },
  {
    id: 30,
    name: "Akari 26N",
    amount: 2,
    year: 1977,
    cost: 400,
    color: "beige",
    producer: "Icamu Noguchi",
    image: "https://www.objekt-vintage.nl/wp-content/uploads/2022/07/noguchi-6.jpg",
    designer: "ISAMU NOGUCHI",
    type: "lamp",
    popularity: 106,
    isInCart:  false,
  },
 ]

 if (localStorage.getItem("products") === null) {
  localStorage.setItem('products', JSON.stringify(products))
}
 

